services:
  app:
    build: .
    container_name: campus_assistant_v2_app
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDbSettings__ConnectionString=mongodb://mongo_v2:27017
      - MongoDbSettings__DatabaseName=AICampusDb_V2
    depends_on:
      - mongo_v2
    restart: unless-stopped
    networks:
      - campus_net_v2

  mongo_v2:
    image: mongo:7
    container_name: campus_assistant_v2_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata_v2:/data/db
      - ./Scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    restart: unless-stopped
    networks:
      - campus_net_v2

  mongo-express:
    image: mongo-express:latest
    container_name: campus_assistant_v2_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_v2
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo_v2
    restart: unless-stopped
    networks:
      - campus_net_v2

volumes:
  mongodata_v2:

networks:
  campus_net_v2:
    driver: bridge